name: Lint and Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - uses: pnpm/action-setup@v4
        name: Install pnpm and dependencies
        id: pnpm-install
        with:
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
